AppBundle\Entity\Ddocmap:
    type: entity
    table: ddocmap
    indexes:
        IDX_2FED311C31E478089F44A603:
            columns:
                - idcollection
                - iddoc
    uniqueConstraints:
        ddocmap_unique:
            columns:
                - iddoc
                - idcollection
    id:
        pk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        projection:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
        sheetnumber:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
        oncartesius:
            type: boolean
            nullable: true
    manyToOne:
        idcollection:
            targetEntity: Ddocument
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcollection:
                    referencedColumnName: idcollection
                iddoc:
                    referencedColumnName: iddoc
            orphanRemoval: false
    lifecycleCallbacks: {  }
