AppBundle\Entity\Ddocscale:
    type: entity
    table: ddocscale
    indexes:
        IDX_6ADDF92631E478089F44A603:
            columns:
                - idcollection
                - iddoc
    uniqueConstraints:
        ddocscale_unique:
            columns:
                - idcollection
                - iddoc
                - scale
    id:
        pk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        scale:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        idcollection:
            targetEntity: Ddocument
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcollection:
                    referencedColumnName: idcollection
                iddoc:
                    referencedColumnName: iddoc
            orphanRemoval: false
    lifecycleCallbacks: {  }
