AppBundle\Entity\Dlinklocsam:
    type: entity
    table: dlinklocsam
    indexes:
        IDX_A8D4CB9BB28ADCE995B6DB6F:
            columns:
                - idcollecsample
                - idsample
        IDX_A8D4CB9BC6C028CA50E3C8BA3D607B62:
            columns:
                - idcollectionloc
                - idpt
                - idstratum
    uniqueConstraints:
        dlinklocsam_unique:
            columns:
                - idcollectionloc
                - idpt
                - idstratum
                - idcollecsample
                - idsample
    id:
        pk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    manyToOne:
        idcollecsample:
            targetEntity: Dsample
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcollecsample:
                    referencedColumnName: idcollection
                idsample:
                    referencedColumnName: idsample
            orphanRemoval: false
        idcollectionloc:
            targetEntity: Dloclitho
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcollectionloc:
                    referencedColumnName: idcollection
                idpt:
                    referencedColumnName: idpt
                idstratum:
                    referencedColumnName: idstratum
            orphanRemoval: false
    lifecycleCallbacks: {  }
