AppBundle\Entity\Dlochydro:
    type: entity
    table: dlochydro
    indexes:
        IDX_A3F3E7D131E4780850E3C8BA:
            columns:
                - idcollection
                - idpt
    uniqueConstraints:
        dlochydro_unique:
            columns:
                - idcollection
                - idpt
                - hydroinfo
                - hydroname
    id:
        pk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        hydroinfo:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
        hydroname:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
        tributaryof:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        idcollection:
            targetEntity: Dloccenter
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcollection:
                    referencedColumnName: idcollection
                idpt:
                    referencedColumnName: idpt
            orphanRemoval: false
    lifecycleCallbacks: {  }
