AppBundle\Entity\Dloccarto:
    type: entity
    table: dloccarto
    indexes:
        IDX_F7FD1F431E4780850E3C8BA:
            columns:
                - idcollection
                - idpt
    uniqueConstraints:
        dloccarto_unique:
            columns:
                - idcollection
                - idpt
                - cartoref
    id:
        pk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        cartoref:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
        cartoname:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
        cartoinfo:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        idcollection:
            targetEntity: Dloccenter
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcollection:
                    referencedColumnName: idcollection
                idpt:
                    referencedColumnName: idpt
            orphanRemoval: false
    lifecycleCallbacks: {  }
