AppBundle\Entity\Dsamheavymin2:
    type: entity
    table: dsamheavymin2
    indexes:
        IDX_E1820DFE31E4780895B6DB6F:
            columns:
                - idcollection
                - idsample
    uniqueConstraints:
        dsamheavymin2_unique:
            columns:
                - idcollection
                - idsample
                - mineral
    id:
        pk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        mineral:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
        minnum:
            type: smallint
            nullable: true
            options:
                unsigned: false
        observationhm:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        idcollection:
            targetEntity: Dsamheavymin
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcollection:
                    referencedColumnName: idcollection
                idsample:
                    referencedColumnName: idsample
            orphanRemoval: false
    lifecycleCallbacks: {  }
