AppBundle\Entity\Lminerals:
    type: entity
    table: lminerals
    uniqueConstraints:
        lminerals_unique:
            columns:
                - idmineral
    id:
        pk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        idmineral:
            type: integer
            nullable: false
            options:
                unsigned: false
        rank:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
        fmname:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
        mname:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
        mformula:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
        fmparent:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
        mparent:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
